name: Docker Build and Push

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  docker_publish:
    name: Docker Build and Push
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Branch Name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SANITIZED_BRANCH_NAME=${BRANCH_NAME//\//-}
          echo "BRANCH_NAME=$SANITIZED_BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and Push Docker Image with Branch Tag
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ env.BRANCH_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image with Semver Tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
